travis:
  secure:
    BINSTAR_TOKEN: wVH/hEPQDXKjjIIeUW851F5suKD17ZjwUBRE951ILRQh0yXufkMCIWb5OFT4l7RsTpmO/l5bUKXdlFRVykmFHarfCZGJVejgnlKRgKwndjy8AKSXaFmZ8XI2ybv1bdSY1wS5GZLAxv9bUpIdpKGRSO+N95mNLFoJHl+41kPVL5WTjBVOISzTS0id9UZCaB52j/ndT3s/CS2sth7GEsQpHnXaM+XgET4FOTyVeVIccGhrdqX7tA7cwYKUSCjHRS1YTdk+dsDoDx+A8HGugaWngro/1ijH1ZGkTAblpB43u5qXKB5wUdB2wbqhc24G876YmXIQI3EvEvxcHeiNUsFM8R1VQnu/0WS41bMMOb5SkIMCRt3CoLtPZgS1Sgstg6i85VHSia6PuZ8oYpleDTaY9PxrJKQDaI9m1XtrREYNNHaVmPPV+lyOmUIYLTEopGLJFgbC3Ha7XuRRy4jh/56thIZP8J/BpSfHZXqhKEAQeGmDxw1pXRWkM+7zoK/LfYpQIwDdRfrpz1sDRqdnKyRFGiNkvCc2p754403GcdbTg8wuO3TItjSyCckKFFIVPAwhMSgUUtmHZrGI3esRko/4h74/KeWR1xbm04h+gCBcaUpEQ9LeokmyLJDJr4nJFKt3GpgygAAoG5tBgL13PPFW9ugtzU8vFaYaiiWW2T38c6E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
